import { Button } from "@mui/material";
import { useContext } from "react";
import { Link } from "react-router-dom";
import { CartContext } from "./CartContext";
import DeleteOutlinedIcon from '@mui/icons-material/DeleteOutlined';
import Tooltip from '@mui/material/Tooltip';
import { serverTimestamp, setDoc, doc, collection, updateDoc, increment } from "firebase/firestore";
import { db } from "../utils/firebaseConfig"

const Cart = () => {

    const { cartList, clear, removeItem, totalPurchease } = useContext( CartContext );

    const createOrder = () => {
        let order = {
            buyer: {
                name: "Vita PS",
                email: "vita.piSan@gmail.com",
                phone: 234234234,
            },
            items: cartList.map(e => ({
                id: e.id,
                title: e.titulo,
                price: e.precio,
                qty: e.qtyItem
            })),
            date: serverTimestamp(),
            total: totalPurchease()
        }
        

        const setOrderInDb = async() => {
            const newOrderRef = doc(collection(db, "orders")) //this line is to asign to an order an automatic id generated by DB.
            await setDoc(newOrderRef, order);
            return newOrderRef
        }

        setOrderInDb()
            .then(res => {
                cartList.forEach( async(e) => {
                    const productRef = doc(db, "products", e.id);
                    await updateDoc(productRef, {
                        stock: increment(-e.qtyItem)
                    });
                });
                clear()
            })
            .catch(err => console.log(err))
    }
    

    return (
        <>
        <div>
            <h1 style={{color:"gray", display:"flex", justifyContent:"center"}}>Carrito de Compras</h1>
            <div>
            {
                cartList.length === 0 
                ? ( 
                    <div className="cartContainer"><p style={{ color:"white"}}>Tu carrito está vacío.</p>
                    <Link to="/" style={{textDecoration: "none"}}> <Button  variant="contained" color="secondary">Ver Productos</Button></Link></div> )
                :  (
                    cartList.map( e => <div className="itemsCart" key={e.id}>
                    <Tooltip title="Eliminar"><DeleteOutlinedIcon color="secondary" onClick={() => removeItem(e.id)} style={{cursor:"pointer", fontSize:"40px"}}/></Tooltip>
                    <img src={e.imagen} alt="" style={{ borderRadius: "10px", width:"140px" }} />
                    <h1 style={{color:"white", fontSize:"25px"}}>   {e.titulo} - {e.qtyItem} unidad/es - Sub-Total ${e.precio * e.qtyItem}</h1></div>)   
                )
            }
            </div>
            { 
                (cartList.length !== 0) &&
                    <div style={{display:"flex", justifyContent:"space-evenly"}}>
                        <h1 className="divTotalPrice">Total: ${totalPurchease()}</h1>
                    </div>
            }
            {
                cartList.length !== 0
                ? (<div style={{display:"flex", justifyContent: "space-evenly"}}><Button variant="outlined" onClick={clear} color="secondary">Vaciar Carrito</Button><Button variant="outlined" color="secondary" onClick={()=>createOrder()}>Finalizar Compra</Button></div>)
                : (<></>) 
            }
        </div>
        </>
    )
}

export default Cart;